test_unorderset:test_unorderset.cpp
	g++ -g -std=c++11 $^ -o $@
test_unordermap:test_unordermap.cpp
	g++ -g -std=c++11 $^ -o $@
test_set:test_set.cpp
	g++ -g -std=c++11 $^ -o $@
test_map:test_map.cpp
	g++ -g -std=c++11 $^ -o $@

