Insert_Sort:Insert_Sort.cpp
	g++ -g -std=c++11 $^ -o $@ 
Select_Sort:Select_Sort.cpp
	g++ -g -std=c++11 $^ -o $@ 
Heap_Sort:Heap_Sort.cpp
	g++ -g -std=c++11 $^ -o $@ 
Megre_Sort:Megre_Sort.cpp
	g++ -g -std=c++11 $^ -o $@ 
Quick_Sort:Quick_Sort.cpp
	g++ -g -std=c++11 $^ -o $@ 
